FROM algmprivsecops/moodle_cli:latest 

WORKDIR /app

COPY ./config-dist.php /app/public/config.php

ENV APP_ENV=${LAGOON_ENVIRONMENT_TYPE}
ENV WEBROOT=public
ENV PAGER=less
ENV PHP_MEMORY_LIMIT=8192M
